environment:
  global:
    TOXENV: py,codecov

  matrix:
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python27-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -U tox

build: false

test_script:
  - python -m tox

branches:
  only:
    - master
    - /^.*-maintenance$/

cache:
  - '%LOCALAPPDATA%\pip\Cache'
